In [1]:
import pandas as pd
import numpy as np

Data Preparation

In [2]:
data_source = pd.read_csv('./Source/adult11.csv')

data_source.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,salary
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

Exploring the dataset

In [3]:
col = [c for c in data_source.columns]
print (f"Columns found inside the dataset are: {col}")

Columns found inside the dataset are: ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'salary']

In [4]:
print(data_source.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       48842 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      48842 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   gender          48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48842 non-null  object
 14  salary          48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB
None

In [5]:
print(data_source.describe())

                age        fnlwgt  education-num  capital-gain  capital-loss  \
count  48842.000000  4.884200e+04   48842.000000  48842.000000  48842.000000
mean      38.643585  1.896641e+05      10.078089   1079.067626     87.502314
std       13.710510  1.056040e+05       2.570973   7452.019058    403.004552
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.175505e+05       9.000000      0.000000      0.000000
50%       37.000000  1.781445e+05      10.000000      0.000000      0.000000
75%       48.000000  2.376420e+05      12.000000      0.000000      0.000000
max       90.000000  1.490400e+06      16.000000  99999.000000   4356.000000

       hours-per-week
count    48842.000000
mean        40.422382
std         12.391444
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000

In [6]:
print(data_source.dtypes)

age                int64
workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
gender            object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
salary            object
dtype: object

In [7]:
integer_types = [col for col, dtype in data_source.dtypes.items() if np.issubdtype(dtype, np.integer)]
print(f"Numerical columns are: {integer_types}")

Numerical columns are: ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week']

Statistics calculations on numerical data types

In [8]:
numeric_data_values = data_source.select_dtypes(include = 'number')
mean_values = numeric_data_values.mean()
print(f"MEAN VALUES\n {mean_values}\n")
median_values = numeric_data_values.median()
print(f"MEDIAN VALUES\n{median_values}\n")
mode_values = numeric_data_values.mode()
print(f"MODE VALUES\n{mode_values}\n")
sd_values = numeric_data_values.std()
print(f"STANDARD DEVIATION\n{sd_values}\n")

MEAN VALUES
 age                   38.643585
fnlwgt            189664.134597
education-num         10.078089
capital-gain        1079.067626
capital-loss          87.502314
hours-per-week        40.422382
dtype: float64

MEDIAN VALUES
age                   37.0
fnlwgt            178144.5
education-num         10.0
capital-gain           0.0
capital-loss           0.0
hours-per-week        40.0
dtype: float64

MODE VALUES
   age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
0   36  203488              9             0             0              40

STANDARD DEVIATION
age                   13.710510
fnlwgt            105604.025423
education-num          2.570973
capital-gain        7452.019058
capital-loss         403.004552
hours-per-week        12.391444
dtype: float64

Correlation between features

In [13]:
correlation_matrix = numeric_data_values.corr()
correlation_matrix

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
age,1.000000,-0.076628,0.030940,0.077229,0.056944,0.071558
fnlwgt,-0.076628,1.000000,-0.038761,-0.003706,-0.004366,-0.013519
education-num,0.030940,-0.038761,1.000000,0.125146,0.080972,0.143689
capital-gain,0.077229,-0.003706,0.125146,1.000000,-0.031441,0.082157
capital-loss,0.056944,-0.004366,0.080972,-0.031441,1.000000,0.054467
hours-per-week,0.071558,-0.013519,0.143689,0.082157,0.054467,1.000000